### ISSUE TITLE
A minimalisitc RSI signal script with open api

### ISSUE THREAD

**Issue by bluetyphoon77** [madpowah/BotCoinAnalyzer#2]
Hi ;)
I was searching for examples of little bots using free api's rather than binance or any exchange where kyc is needed.
I would love to ask you, how many lines would it take to write a script just printing a signal when BTCUSDT weekly RSI reached a specific level ? I'm a beginner and I would love to start with the most minimalistic script possible using Ta-lib or open API.
Would you be able to help ? I'd be ok to pay you for the writing of those lines... Please keep in touch ;)
thanks in advance

**Comment by madpowah** [comment]
Look at the coin.py file and the rsiAlert() method. This method already does what you want.

**Comment by bluetyphoon77** [comment]
thanks. Without needing any API ?

**Comment by madpowah** [comment]
Yes of course you need to call an apy. Binance.py gives you the api. It checks all btc pairs. You import binance.py, you create a binance object and call checkAllInfoValues() and then you call rsiAlert() like line 270 in coinanalyze.py

**Comment by bluetyphoon77** [comment]
Wow great !
Are you using Talib or something else ?
Is it also possible to talk privately if it would be possible to hire your services to code ;) I'm not sure I'll be able to do it

**Comment by madpowah** [comment]
Yes i use Talib
cloud at madpowah dot org
